### ISSUE TITLE
Work with full version of Kendo UI?

### ISSUE THREAD

**Issue by KhoaSydney** [jampy/kendo-ui-webpack#2]
Hi Jampy,

Is this project still active? Will this work with full version of Kendo UI instead of Kendo UI Core? This looks very promising. Please let me know.

Cheers,
Khoa

**Comment by jampy** [comment]
Hi KhoaSydney. Actually I myself never started using it because I switched to React with Material UI instead of using Kendo UI.

It should work I think. If you have a look at the source code you'll notice it's just a wrapper and it should be easy to customize/extend it for additional components.
