### ISSUE TITLE
Context Menu

### ISSUE THREAD

**Issue by hosain-cse2** [jampy/kendo-ui-webpack#4]
Hi,

Can you please tell me how can I use the context menu?
I am importing the ContextMenu as following,

require("kendo-ui-webpack/kendo.ui.ContextMenu");
jQuery("#context-menu").kendoMenu({
            target: "#target",
            alignToAnchor: true,
            orientation: "vertical"
        });

But it is giving me a normal menu instead of a context menu. It will be bery helpful if you can give me a solution.

Regards,
Hosain

**Comment by jampy** [comment]
I'm sorry but I can't help you with this. I wrote this module mainly for myself but I never actually started using Kendo, really (because I preferred React with Material UI).
